name: Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check files
        run: ls -n /Applications/ | grep Xcode*

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer

      - name: Test
        run: xcodebuild -workspace ./Example/ShippedSuite.xcworkspace -scheme ShippedSuite-Example -enableCodeCoverage YES -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 12' build test

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --without=documentation --jobs 4 --retry 3

      - name: Upload code coverage report
        run: bundle exec slather

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
